<?php
declare(strict_types=1);

// LaunchLibrary2 SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

LaunchLibrary2Utility::setRegistrar(function (LaunchLibrary2Utility $u): void {
    $u->clean = [LaunchLibrary2Clean::class, 'call'];
    $u->done = [LaunchLibrary2Done::class, 'call'];
    $u->make_error = [LaunchLibrary2MakeError::class, 'call'];
    $u->feature_add = [LaunchLibrary2FeatureAdd::class, 'call'];
    $u->feature_hook = [LaunchLibrary2FeatureHook::class, 'call'];
    $u->feature_init = [LaunchLibrary2FeatureInit::class, 'call'];
    $u->fetcher = [LaunchLibrary2Fetcher::class, 'call'];
    $u->make_fetch_def = [LaunchLibrary2MakeFetchDef::class, 'call'];
    $u->make_context = [LaunchLibrary2MakeContext::class, 'call'];
    $u->make_options = [LaunchLibrary2MakeOptions::class, 'call'];
    $u->make_request = [LaunchLibrary2MakeRequest::class, 'call'];
    $u->make_response = [LaunchLibrary2MakeResponse::class, 'call'];
    $u->make_result = [LaunchLibrary2MakeResult::class, 'call'];
    $u->make_point = [LaunchLibrary2MakePoint::class, 'call'];
    $u->make_spec = [LaunchLibrary2MakeSpec::class, 'call'];
    $u->make_url = [LaunchLibrary2MakeUrl::class, 'call'];
    $u->param = [LaunchLibrary2Param::class, 'call'];
    $u->prepare_auth = [LaunchLibrary2PrepareAuth::class, 'call'];
    $u->prepare_body = [LaunchLibrary2PrepareBody::class, 'call'];
    $u->prepare_headers = [LaunchLibrary2PrepareHeaders::class, 'call'];
    $u->prepare_method = [LaunchLibrary2PrepareMethod::class, 'call'];
    $u->prepare_params = [LaunchLibrary2PrepareParams::class, 'call'];
    $u->prepare_path = [LaunchLibrary2PreparePath::class, 'call'];
    $u->prepare_query = [LaunchLibrary2PrepareQuery::class, 'call'];
    $u->graphql_body = [LaunchLibrary2Graphql::class, 'body'];
    $u->graphql_errors = [LaunchLibrary2Graphql::class, 'errors'];
    $u->result_basic = [LaunchLibrary2ResultBasic::class, 'call'];
    $u->result_body = [LaunchLibrary2ResultBody::class, 'call'];
    $u->result_headers = [LaunchLibrary2ResultHeaders::class, 'call'];
    $u->transform_request = [LaunchLibrary2TransformRequest::class, 'call'];
    $u->transform_response = [LaunchLibrary2TransformResponse::class, 'call'];
});
